# restore Host NetworkManager.conf

- name: unlock /etc/resolv.conf to avoid to be rewritten at startup
  shell: chattr -i /etc/resolv.conf

- name: remove dns virtual machine ip {{ dns_ip }} entry into /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    state: absent
    regexp: '^nameserver {{ dns_ip }}'
    backup: yes

- name: reload NetworkManager service
  shell: systemctl reload NetworkManager
