---
# tasks file for delete-guest-virtual-machine
- include_tasks: assert_preconditions.yml

- name: delete {{ vm_name }}
  block:
    - name: delete {{ vm_name }} virtual machine data
      file:
        path: "/home/{{ ansible_user_id }}/.okd/vms/{{ vm_name }}"
        state: absent

    - name: list virtual machines
      virt:
        command: list_vms
        uri: "qemu:///session"
      register: vms

    - debug:
        msg: "{{ vms.list_vms }}"

    - name: destroy {{ vm_name }} virtual machine
      virt:
        command: destroy
        name: "{{ vm_name }}"
        uri: "qemu:///session"
      ignore_errors: yes
      when: vm_name in vms.list_vms

    - name: undefine {{ vm_name }} virtual machine
      virt:
        command: undefine
        name: "{{ vm_name }}"
        uri: "qemu:///session"
      ignore_errors: yes
      when: vm_name in vms.list_vms

    - name: remove {{ vm_name }} data
      file:
        path: "{{item}}"
        state: absent
      with_fileglob:
        - "/tmp/container_registry.*"
      become: true
      become_user: root

    - name: remove {{ vm_name }} virtual machine host from known_hosts
      lineinfile:
        path: "/home/{{ ansible_user_id }}/.ssh/known_hosts"
        state: absent
        regexp: '^.*{{ vm_ip }}.*$'
  become_user: "{{ ansible_user_id }}"

- include_tasks: dns.yml
  when: vm_ip == dns_ip

- include_tasks: okd_master.yml
  when: vm_ip == okd_master_ip