- name: flush /data/logging content in nfs virtual machine
  shell: ssh {{ ansible_user_id }}@{{ nfs_ip }} 'sudo rm -rf /data/logging/*'

- name: flush /data/registry content in nfs virtual machine
  shell: ssh {{ ansible_user_id }}@{{ nfs_ip }} 'sudo rm -rf /data/registry/*'

- name: flush /data/metrics content in nfs virtual machine
  shell: ssh {{ ansible_user_id }}@{{ nfs_ip }} 'sudo rm -rf /data/metrics/*'
