---
- name: This playbook install OKD projects on a local server
  hosts: localhost

  vars:
    okd_master_fqdn: "master.okd.local"

  tasks:
    - name: install ci/cd
      block:
        - name: create ci/cd project
          shell: ssh {{ ansible_user_id }}@{{ okd_master_fqdn }} 'oc new-project ci-cd --display-name="CI/CD" --description="CI/CD Components (Jenkins, Nexus, Pipeline)"'

        ################################################################################################################
        # nexus
        ################################################################################################################
        - name: handle nexus persistent volume
          include_role:
            name: create-persistent-volume
          vars:
            - name: "nexus"
            - vm_fqdn: "master.okd.local"

        - name: copy nexus template
          shell: scp -r -p nexus-persistent-template.yml {{ ansible_user_id }}@{{ okd_master_fqdn }}:/tmp/nexus-persistent-template.yml

        - name: deploy nexus
          shell: ssh {{ ansible_user_id }}@{{ okd_master_fqdn }} 'oc process -f /tmp/nexus-persistent-template.yml | oc create -n ci-cd -f -'

        - name: update nexus resources
          shell: ssh {{ ansible_user_id }}@{{ okd_master_fqdn }} 'oc set resources dc/nexus --limits=cpu=1,memory=1Gi --requests=cpu=200m,memory=1Gi -n ci-cd'

        - name: wait until nexus deployment is finished
          shell: ssh {{ ansible_user_id }}@{{ okd_master_fqdn }} 'oc rollout status dc/nexus -n ci-cd'
          register: task_result
          until: "'successfully' in task_result.stdout"
          retries: 120
          delay: 5

        ################################################################################################################
        # jenkins
        ################################################################################################################
        - name: handle nexus persistent volume
          include_role:
            name: create-persistent-volume
          vars:
            - name: "jenkins"
            - vm_fqdn: "master.okd.local"

        # template coming from https://raw.githubusercontent.com/openshift/origin/master/examples/jenkins/jenkins-persistent-template.json
        # my template just add a matchLabels on PVC
        - name: copy jenkins template
          shell: scp -r -p jenkins-persistent-template.yml {{ ansible_user_id }}@{{ okd_master_fqdn }}:/tmp/jenkins-persistent-template.yml

        # Deploy an old version of openshift jenkins to fix issue with the last version of openshift-login (1.0.22) by downgrading to version 1.0.19 and
        # an access denied issue when creating jenkins workspace.
        - name: push jenkins-2-centos7:e2a35ea into okd internal registry
          block:
            - name: tag image to internal registry
              shell: ssh {{ ansible_user_id }}@{{ okd_master_fqdn }} 'docker tag docker.io/openshift/jenkins-2-centos7:e2a35ea docker-registry.default.svc:5000/openshift/jenkins:e2a35ea'

            - name: log and push image into internal registry
              shell: ssh {{ ansible_user_id }}@{{ okd_master_fqdn }} 'oc login -u damien -p damien && docker login -p $(oc whoami -t) -u unused docker-registry.default.svc:5000 && docker push docker-registry.default.svc:5000/openshift/jenkins:e2a35ea'

        - name: deploy jenkins
          shell: ssh {{ ansible_user_id }}@{{ okd_master_fqdn }} 'oc new-app -f /tmp/jenkins-persistent-template.yml -p JENKINS_IMAGE_STREAM_TAG=jenkins:e2a35ea -p MEMORY_LIMIT=1Gi -e INSTALL_PLUGINS=ssh-agent:1.15 -l app=jenkins -n ci-cd'

        - name: wait until jenkins deployment is finished
          shell: ssh {{ ansible_user_id }}@{{ okd_master_fqdn }} 'oc rollout status dc/jenkins -n ci-cd'
          register: task_result
          until: "'successfully' in task_result.stdout"
          retries: 120
          delay: 5

    - name: handle event data spreader library
      block:
        - name: handle maven-repo persistent volume
          include_role:
            name: create-persistent-volume
          vars:
            - name: "maven-repo"
            - vm_fqdn: "master.okd.local"

        - name: install event data spreader pipeline
          shell: ssh {{ ansible_user_id }}@{{ okd_master_fqdn }} 'oc process -f https://raw.githubusercontent.com/dcdh/event-data-spreader/master/templates/event-data-spreader-build-pipeline.yml | oc create -f - -n ci-cd'

