---
- name: This playbook uninstall OKD 3.11 from a local server
  hosts: localhost

  vars:
    bridge_name: "virbr5"
    dns_ip: "10.0.5.10"
    dns_fqdn: "dns.local"
    nfs_ip: "10.0.5.12"
    nfs_fqdn: "nfs.local"
    container_registry_ip: "10.0.5.11"
    container_registry_fqdn: "container-registry.okd.local"
    okd_master_ip: "10.0.5.50"
    okd_master_fqdn: "master.okd.local"

  tasks:
    - name: delete dns guest virtual machine
      include_role:
        name: delete-guest-virtual-machine
      vars:
        - vm_name: "{{ dns_fqdn }}"
        - vm_ip: "{{ dns_ip }}"

    - name: delete container registry guest virtual machine
      include_role:
        name: delete-guest-virtual-machine
      vars:
        - vm_name: "{{ container_registry_fqdn }}"
        - vm_ip: "{{ container_registry_ip }}"

    - name: delete nfs guest virtual machine
      include_role:
        name: delete-guest-virtual-machine
      vars:
        - vm_name: "{{ nfs_fqdn }}"
        - vm_ip: "{{ nfs_ip }}"

    - name: delete okd all in one master guest virtual machine
      include_role:
        name: delete-guest-virtual-machine
      vars:
        - vm_name: "{{ okd_master_fqdn }}"
        - vm_ip: "{{ okd_master_ip }}"

    - name: delete {{ bridge_name }} vlan network
      include_role:
        name: delete-vlan-network