---
- name: This playbook uninstall OKD 3.11 from a local server
  hosts: localhost
  vars:
    installer_path: "/home/{{ ansible_user_id }}/.okd"
  tasks:
    - name: "[HOST] Delete OKD network"
      include: delete_vlan_network.yaml
      vars:
        bridge_name: "virbr1"
