---
- name: This playbook uninstall OKD 3.11 from a local server
  hosts: localhost

  vars:
    bridge_name: "virbr5"
    dns_ip: "10.0.5.10"
    dns_fqdn: "dns.local"
    okd_all_in_one_ip: "10.0.5.50"
    okd_all_in_one_fqdn: "master.okd.local"

  vars_prompt:
    - name: ansible_become_password
      prompt: "What is your password ?"
      private: yes

  tasks:
    - include_role:
        name: delete-guest-virtual-machine
      vars:
        - vm_name: "{{ dns_fqdn }}"
        - vm_ip: "{{ dns_ip }}"
        - is_dns_vm: true

    - include_role:
        name: delete-guest-virtual-machine
      vars:
        - vm_name: "{{ okd_all_in_one_fqdn }}"
        - vm_ip: "{{ okd_all_in_one_ip }}"
        - is_dns_vm: false

    - include_role:
        name: delete-vlan-network