# check dnsmasq service is active
- name: should dnsmasq service be active on {{ vm_name }}
  shell: ssh {{ ansible_user_id }}@{{ vm_ip }} 'sudo systemctl is-active dnsmasq'
  register: task_result
  until: task_result.stdout == 'active'
  retries: 120
  delay: 5