- name: create user conf
  copy:
    dest: /etc/qemu-kvm/{{ ansible_user_id }}.conf
    content: |
      allow all
    mode: 640
    owner: root
    group: "{{ ansible_user_id }}"
- name: include user conf in bridge.conf if not present
  lineinfile:
    path: /etc/qemu-kvm/bridge.conf
    state: present
    line: "include /etc/qemu-kvm/{{ ansible_user_id }}.conf"
    backup: yes
