#    Add dns entry into Host to be able to access virtual machine in '.sandbox.okd'.
#    Howto do in Centos7 explains here : https://access.redhat.com/solutions/2817911
#    It seems that it is not working as expected after rebooting. So I lock /etc/resolv.conf to ensure
#    that no one will change it !
- name: add {{ vm_name }} virtual machine ip {{ vm_ip }} entry into /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver {{ vm_ip }}'
    insertbefore: BOF
    line: nameserver {{ vm_ip }}
    backup: yes

- name: lock /etc/resolv.conf to avoid to be rewritten at startup
  shell: chattr +i /etc/resolv.conf

- name: reload NetworkManager service
  shell: systemctl reload NetworkManager