- name: assert bridge_name variable is defined
  assert:
    that:
      - "bridge_name is defined and bridge_name"
    fail_msg: "bridge_name must be define"
    success_msg: "bridge_name define to {{ bridge_name }}"
