- name: enable IP forwarding / masquerading
  block:
    - name: enable on the fly IP forwarding / masquerading
      shell: sysctl -w net.ipv4.ip_forward=1
    - name: persist IP forwarding / masquerading
      copy:
        dest: /etc/sysctl.d/99-openshift.conf
        src: 99-openshift.conf
        mode: u=rw,g=r,o=r
        owner: root
        group: root
    - name: reboot sysctl
      shell: sysctl -p

- name: add firewall rules to allow ip forwarding / masquerading
  block:
# setup iptables rules on Host to allow SSH to connect on the fly instead of hanging ...
# https://stackoverflow.com/questions/25055121/can-i-remove-multiple-matching-rules-with-the-iptables-delete-command
    - name: remove all previous forward rules regarding {{ bridge_name }}
      shell: "iptables -S FORWARD | grep {{ bridge_name }} | cut -d ' ' -f 2- | xargs -rL1 iptables -D"
    - name: forward all input in interface {{ bridge_name }}
      shell: "iptables -I FORWARD 1 --in-interface {{ bridge_name }} -j ACCEPT"
    - name: forward all output out interface {{ bridge_name }}
      shell: "iptables -I FORWARD 1 --out-interface {{ bridge_name }} -j ACCEPT"

- name: allow all virtual machine connected to bridge {{ bridge_name }} to access to internet using nat from Host
  block:
    - name: retrieve interface connected to internet
      shell: ip route | grep default | cut -d " " -f 5
      register: interface_connected_to_internet
    - name: bind interface {{ bridge_name }} with {{ interface_connected_to_internet.stdout }}
      shell: "iptables -t nat -I POSTROUTING -o {{ interface_connected_to_internet.stdout }} -j MASQUERADE"
    - name: save iptable rules
      shell: "service iptables save"

#        - name: Should {{ bridge_name }} be forwarded HOW TO TEST ???
